AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/*'
    - 'Guardfile'
    - 'lib/tasks/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'features/support/env.rb'

Metrics/LineLength:
  Max: 100

Documentation:
  Enabled: false
